title: Kho Lưu Trữ Cá Nhân Tự Động
email: your-email@example.com
description: >-
  Đây là một Repository tự động hóa bằng GitHub Actions và Jekyll.
baseurl: ""
url: "https://<Tên_tài_khoản>.github.io/<Tên_Repo>" 
encoding: utf-8
permalink: pretty

# CẦN BỔ SUNG HOẶC CHỈNH SỬA PHẦN NÀY:
include:
  - hinh-anh-ki-niem/ # <-- BỔ SUNG DÒNG NÀY ĐỂ BUỘC JEKYLL SAO CHÉP TOÀN BỘ THƯ MỤC
  - hinh-anh-ki-niem/nam-2016/ # <-- BỔ SUNG DÒNG NÀY (cần thiết nếu Jekyll bỏ qua)
  
exclude:
  - Gemfile
  - Gemfile.lock
  - _scripts/
  - .github/
  - vendor/
