title: Kho Lưu Trữ Cá Nhân Tự Động
email: your-email@example.com
description: >-
  Đây là một Repository tự động hóa bằng GitHub Actions và Jekyll.
baseurl: ""
url: "https://<Tên_tài_khoản>.github.io/<Tên_Repo>" 
encoding: utf-8
permalink: pretty

# BỔ SUNG HOẶC CHỈNH SỬA PHẦN NÀY:
exclude:
  - Gemfile
  - Gemfile.lock
  - _scripts/
  - .github/
  - vendor/  # <--- BẮT BUỘC PHẢI THÊM DÒNG NÀY
